import type { Metadata } from "next";
import { Geist, Geist_Mono, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "./layouts/NavBar/NavBar";
import WrapperSection from "./layouts/WrapperSection";
import Hero from "./components/Hero";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${beVietnamPro.className} antialiased`}>
        <ThemeProvider attribute="class">
          <Navbar />
          <Hero />
          <WrapperSection>{children}</WrapperSection>
        </ThemeProvider>
      </body>
    </html>
  );
}
